"""empty message

Revision ID: af1fdad5d212
Revises: dde7be9419d2
Create Date: 2023-01-30 11:54:16.227699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af1fdad5d212'
down_revision = 'dde7be9419d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.alter_column('accessibility',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_column('test1')
        batch_op.drop_column('test2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test2', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('test1', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.alter_column('accessibility',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
