"""empty message

Revision ID: cc3636ac792b
Revises: 066ef74e5dc1
Create Date: 2023-01-31 16:14:14.084804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc3636ac792b'
down_revision = '066ef74e5dc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweets', schema=None) as batch_op:
        batch_op.drop_constraint('tweets_retweet_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweets', schema=None) as batch_op:
        batch_op.create_foreign_key('tweets_retweet_id_fkey', 'tweets', ['retweet_id'], ['id'])

    # ### end Alembic commands ###
