"""test columns

Revision ID: dde7be9419d2
Revises: d5d513fd5b2a
Create Date: 2023-01-30 11:41:52.395149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dde7be9419d2'
down_revision = 'd5d513fd5b2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test1', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('test2', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('test2')
        batch_op.drop_column('test1')

    # ### end Alembic commands ###
